- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python3-debian
    state: present
    update_cache: true
  tags: packages
- name: Add docker CE Repo
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/debian/gpg
- name: Update apt and install docker-ce
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
- name: "Add current user to docker group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
- name: "Add noc users to docker group"
  ansible.builtin.user:
    name: "{{ item.unix_name }}"
    groups: docker
    append: true
  loop: "{{ users_list }}"
- name: Install /etc/docker/daemon.json
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    mode: '644'
