services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - services-monitoring_default
      - system_default
    ports:
      - 9090:9090
    restart: always
#    deploy:
#      labels:
#        - "traefik.enable=true"
#        - "traefik.docker.network=system_default"
#        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
#        - "traefik.http.routers.prometheus.rule=Host(`prometheus.apps.hskrk.pl`)"
#        - "traefik.http.routers.prometheus.tls=true"
#        - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
#        - "traefik.http.routers.prometheus.middlewares=authentik@docker"

  nut_exporter:
    image: ghcr.io/druggeri/nut_exporter:latest
    restart: always
    network_mode: "host" # Don't want to bother with setting up NUT authorization, so use host networking to access localhost
    # Listens on port 9199 by default
    environment:
      - NUT_EXPORTER_VARIABLES=battery.charge,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,ups.load,ups.status,ups.temperature,output.current,output.current.nominal,output.voltage,output.voltage.nominal
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - services-monitoring_default
    restart: always

networks:
  system_default:
    external: true
  services-monitoring_default:
    internal: true

volumes:
  prometheus_data:
