services:
  mqtt:
    image: eclipse-mosquitto    
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    secrets:
        - mqtt_pwfile
    networks:
        - mqtt

networks:
    mqtt:
secrets:
    mqtt_pwfile:
        file: /opt/secrets/mqtt_pwfile
