# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_red'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: [ '10.12.20.97:1880' ]
  - job_name: 'powermetery'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: [ '10.12.20.20:80', '10.12.20.21:80' ]
  - job_name: 'frigate'
    scrape_interval: 30s
    metrics_path: /api/metrics
    static_configs:
      - targets: [ '10.12.20.5:5080' ]
  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['flatsun.at.hskrk.pl:9100']
  - job_name: 'nut'
    scrape_interval: 15s
    static_configs:
      - targets: ['flatsun.at.hskrk.pl:9199']
    metrics_path: /ups_metrics
    params:
      ups: ['ups_ces']  # The UPS name to query.
  - job_name: 'cadvisor'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
