services:
  frigate:
    container_name: frigate_hs
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped

    privileged: true

# 2G SHM to bylo za malo nawet na v1 kamer u nas
    shm_size: 3G
    mem_limit: 7G
    deploy:
      resources:
        limits:
          memory: 7G

    devices:
#      - /dev/dri/renderD128
      - /dev/bus/usb:/dev/bus/usb

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf:/config
      - /data/frigate:/media/frigate
#      - ./frigate-tmp:/tmp/cache # Spróbujmy z cache w RAM :D
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1G

    ports:
      - "8666:8666/tcp" # WebRTC over tcp
      - "8666:8666/udp" # WebRTC over udp
      - "5080:5000/tcp" # webpanel
