services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/:/traefik_files/
      - traefik_certificates:/traefik/acme
      - traefik_letsencrypt:/letsencrypt"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 5900
        published: 5900
        protocol: tcp
        mode: host
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik${APPS2_BASE_DOMAIN?no base domain}`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.entrypoints=web"
  whoami:
    image: containous/whoami
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=Host(`whoami${APPS2_BASE_DOMAIN?no base domain}`)"
    networks:
      - traefik
networks:
  traefik:
    attachable: true
volumes:
  traefik_certificates:
  traefik_letsencrypt:
