api:
  insecure: true
  dashboard: true

accessLog:
  format: json

log:
  level: DEBUG

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    network: traefik
  file:
    directory: "/traefik_files"

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/16"
