version: 0.16-0

mqtt:
  enabled: false

birdseye:
  enabled: false
  restream: true
  mode: continuous
  width: 1920
  height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb

# detectors:
#   onnx:
#     type: onnx
# model:
#   #model_type: yolonas
#   width: 320 # <--- should match whatever was set in notebook
#   height: 320 # <--- should match whatever was set in notebook
#   input_pixel_format: bgr
#   input_tensor: nhwc
#   path: /config/yolo_nas_s.onnx
#   labelmap_path: /config/coco-80.txt


detect:
  enabled: true
  fps: 5
  width: 1280
  height: 720

objects:
  track:
    - person

motion:
  threshold: 50
  contour_area: 50

record:
#  sync_recordings: true
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 14
      mode: motion
  detections:
    retain:
      days: 14
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 31
  height: 1080
  clean_copy: true
  crop: false
  bounding_box: true

ffmpeg:
#  global_args: -hide_banner -loglevel info -threads 2
#  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    detect: -threads 1 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac

go2rtc:
  log:
    level: info
    api: info
    exec: info
    ngrok: info
    rtsp: info
    streams: info
    webrtc: info

  webrtc:
    candidates:
      - flatsun.at.hskrk.pl:8666
      - 10.12.20.5:8666
      - stun:8666

  streams:
    domofon: rtsp://10.12.20.10/live/ch00_0
    klatka_schodowa:
      rtsp://admin:HSKrk2137!@10.12.20.50:554/cam/realmonitor?channel=1&subtype=0
    elelab_na_drzwi:
      rtsp://admin:HSKrk2137!@10.12.20.51:554/cam/realmonitor?channel=1&subtype=0
    hardroom_od_okna:
      rtsp://admin:HSKrk2137!@10.12.20.52:554/cam/realmonitor?channel=1&subtype=0
    anc_na_drzwi:
      rtsp://admin:HSKrk2137!@10.12.20.53:554/cam/realmonitor?channel=1&subtype=0
    korytarz_na_wejscie:
      rtsp://admin:HSKrk2137!@10.12.20.54:554/cam/realmonitor?channel=1&subtype=0
    elelab_na_drukarki:
      rtsp://admin:HSKrk2137!@10.12.20.55:554/cam/realmonitor?channel=1&subtype=0
    cnc_na_drukarki:
      rtsp://admin:HSKrk2137!@10.12.20.56:554/cam/realmonitor?channel=1&subtype=0
    maszynownia_na_tokarke:
      rtsp://admin:HSKrk2137!@10.12.20.57:554/cam/realmonitor?channel=1&subtype=0
    kuznia_na_okno:
      rtsp://admin:HSKrk2137!@10.12.20.58:554/cam/realmonitor?channel=1&subtype=0
    audytorium:
      rtsp://admin:HSKrk2137!@10.12.20.59:554/cam/realmonitor?channel=1&subtype=0

#    hardroom_od_drzwi:
#      ffmpeg:rtsp://10.12.5.11:554/user=admin&password=&channel=1&stream=0.sdp?real_stream--rtp-caching=100
#    korytarz_wyjscie:
#      ffmpeg:rtsp://zoneminder:Zoneminder1!@10.12.5.103:554/cam/realmonitor?channel=1&subtype=0#hardware#video=h264#rotate=90
#    magazynek_na_drzwi: ffmpeg:http://zminder:rednimenoz@10.12.5.12/channel1#hardware#video=h264

cameras:
  domofon:
#    detect:
#      enabled: False
#    motion:
#      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/domofon
    record:
      retain:
        days: 1
      alerts:
        retain:
          days: 1
      detections:
        retain:
          days: 1

  klatka_schodowa:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/klatka_schodowa

    motion:
      mask: 0.6,0.037,0.603,0.072,0.964,0.071,0.967,0.039
  elelab_na_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/elelab_na_drzwi

    motion:
      mask: 0.681,0.031,0.683,0.098,0.971,0.097,0.968,0.033
  hardroom_od_okna:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hardroom_od_okna

    motion:
      mask: 0.679,0.037,0.68,0.098,0.968,0.095,0.965,0.033
  anc_na_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/anc_na_drzwi

    motion:
      mask: 0.685,0.038,0.686,0.089,0.967,0.091,0.967,0.04
  korytarz_na_wejscie:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/korytarz_na_wejscie

    motion:
      mask: 0.594,0.039,0.603,0.074,0.967,0.071,0.967,0.039
  elelab_na_drukarki:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/elelab_na_drukarki

    motion:
      mask: 0.015,0.026,0.016,0.08,0.265,0.079,0.266,0.028
  cnc_na_drukarki:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cnc_na_drukarki

    motion:
      mask: 0.749,0.035,0.75,0.075,0.99,0.077,0.99,0.03
  maszynownia_na_tokarke:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/maszynownia_na_tokarke

    motion:
      mask: 0.019,0.033,0.02,0.077,0.26,0.075,0.261,0.033
  kuznia_na_okno:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kuznia_na_okno

    motion:
      mask: 0.016,0.027,0.015,0.082,0.264,0.082,0.265,0.022
  audytorium:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/audytorium
    motion:
      mask: 0.017,0.026,0.018,0.085,0.263,0.084,0.264,0.022
