---
services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    restart: unless-stopped
#    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=hihihaha
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    volumes:
      - ./data:/config
    networks:
      - unifi
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    labels:
      - homepage.group=Networking
      - homepage.name=UniFi Controller
      - homepage.icon=unifi.svg
      - homepage.href=https://flatsun.at.hskrk.pl:8443
      - homepage.description=Ubiquiti UniFi Network Application

  unifi-db:
    image: docker.io/mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=jaquestionmarknienocoty
      - MONGO_USER=unifi
      - MONGO_PASS=hihihaha
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    networks:
        - unifi
    volumes:
      - ./mongo-data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

networks:
    unifi:
