---
- name: Manage Users
  hosts: all
  become: yes
  vars:
    users:
      - { unix_name: "alufers", github_name: "alufers" }
      - { unix_name: "gbdlin", github_name: "gbdlin" }
      - { unix_name: "domints", github_name: "domints" }
      - { unix_name: "zagura", github_name: "zagura" }
      - { unix_name: "pidpawel", github_name: "pidpawel" }
      - { unix_name: "wprzyb", github_name: "wprzyb" }
      - { unix_name: "gregory353a", github_name: "gregory353a" }
      - { unix_name: "hbrylkowski", github_name: "hbrylkowski" }

  tasks:
    - name: Ensure group apps2 exists
      group:
        name: apps2
        state: present
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ item.unix_name }}"
        groups: sudo,docker,apps2
        append: yes
        create_home: yes
        generate_ssh_key: yes
        ssh_key_type: ed25519
        password: ''
        update_password: on_create
      loop: "{{ users }}"
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ item.unix_name }}/.ssh"
        state: directory
        owner: "{{ item.unix_name }}"
        group: "{{ item.unix_name }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Fetch GitHub keys and add to authorized_keys.new
      ansible.builtin.get_url:
        url: "https://github.com/{{ item.github_name }}.keys"
        dest: "/home/{{ item.unix_name }}/.ssh/authorized_keys.new"
        owner: "{{ item.unix_name }}"
        group: "{{ item.unix_name }}"
        mode: '0600'
      loop: "{{ users }}"

    - name: Validate authorized_keys.new with ssh-keygen -lf
      ansible.builtin.shell: ssh-keygen -lf /home/{{ item.unix_name }}/.ssh/authorized_keys.new
      loop: "{{ users }}"
    - name: Move authorized_keys.new to authorized_keys
      ansible.builtin.shell: mv /home/{{ item.unix_name }}/.ssh/authorized_keys.new /home/{{ item.unix_name }}/.ssh/authorized_keys
      loop: "{{ users }}"

