services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped

    privileged: true

    # 2G SHM to bylo za malo nawet na v1 kamer u nas
    shm_size: 4G
    mem_limit: 8G

    devices:
#      - /dev/dri/renderD128
      - /dev/bus/usb:/dev/bus/usb

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /data/frigate:/media/frigate
#      - ./frigate-tmp:/tmp/cache # Spróbujmy z cache w RAM :D
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 3G

    ports:
      - "8666:8666/tcp" # WebRTC over tcp
      - "8666:8666/udp" # WebRTC over udp
      - "5080:5000/tcp" # webpanel
    networks:
      - frigate
      - services-monitoring

networks:
    frigate:
