esphome:
  name: pm-lewy
  friendly_name: pm_lewy

api:
  encryption:
    key: !secret api_key

prometheus:

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  output_power: 11

  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "pm-lewy"
    password: "powermeter"

captive_portal:

web_server:

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

logger:
  level: WARN

uart:
  tx_pin: GPIO40
  rx_pin: GPIO39
  baud_rate: 4800
  parity: NONE
  stop_bits: 1

external_components:
    source: github://ggajoch/power-meter-9000

sensor:
  - platform: uptime
    name: Uptime
  - platform: bl0939addr
    id: chA
    update_interval: 10s
    voltage:
      name: 'v_A'
    current_1:
      name: 'c_Swiatlo A'
    current_2:
      name: 'c_Swiatlo B'
    active_power_1:
      name: 'Swiatlo A'
    active_power_2:
      name: 'Swiatlo B'
    energy_1:
      name: 'e_Swiatlo A'
    energy_2:
      name: 'e_Swiatlo B'
    energy_total:
      name: 'e_A'
    address: 0
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

  - platform: bl0939addr
    id: ch1
    update_interval: 10s
    voltage:
      name: 'v_F1'
    current_1:
      name: 'c_Suma F1'
    current_2:
      name: 'c_Hardroomy empty'
    active_power_1:
      name: 'Suma F1'
    active_power_2:
      name: 'Hardroomy empty'
    energy_1:
      name: 'e_Suma F1'
    energy_2:
      name: 'e_Hardroomy empty'
    energy_total:
      name: 'e_B'
    address: 1
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572
  
  - platform: bl0939addr
    id: ch2
    update_interval: 10s
    voltage:
      name: 'v_F2'
    current_1:
      name: 'c_Suma F2'
    current_2:
      name: 'c_Kuznia'
    active_power_1:
      name: 'Suma F2'
    active_power_2:
      name: 'Kuznia'
    energy_1:
      name: 'e_Suma F2'
    energy_2:
      name: 'e_Kuznia'
    energy_total:
      name: 'e_C'
    address: 2
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

  - platform: bl0939addr
    id: ch3
    update_interval: 10s
    voltage:
      name: 'v_F3'
    current_1:
      name: 'c_Suma F3'
    current_2:
      name: 'c_Maszynownia'
    active_power_1:
      name: 'Suma F3'
    active_power_2:
      name: 'Maszynownia'
    energy_1:
      name: 'e_Suma F3'
    energy_2:
      name: 'e_Maszynownia'
    energy_total:
      name: 'e_D'
    address: 3
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

switch:
  - platform: gpio
    pin: 15
    name: "LED"

binary_sensor:
  - platform: gpio
    name: "button"
    pin: GPIO0

button:
  - platform: restart
    name: "Reboot"
