---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- "Hackerspace Kraków":
    - "Strona główna":
        - abbr: HS
          href: https://hackerspace-krk.pl/

- Github:
    - apps2:
        - abbr: A2
          href: https://github.com/HackerspaceKRK/apps2


