- name: Ensure stacks dir exists
  ansible.builtin.file:
    path: /opt/stacks
    state: directory
    mode: "755"
- name: Check if there are any common stacks
  ansible.builtin.stat:
    path: "{{ role_path }}/stacks/all"
  delegate_to: localhost
  register: common_stacks
- name: Check if there are common stack prerequisites
  when: common_stacks.stat.exists
  ansible.builtin.stat:
    path: "{{ role_path }}/stacks/all/prerequisite.yml"
  delegate_to: localhost
  register: common_stacks_prerequisites
- name: Execute common stack prerequisites
  when: common_stacks.stat.exists and common_stacks_prerequisites.stat.exists
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/stacks/all/prerequisite.yml"
- name: List common stacks
  when: common_stacks.stat.exists
  ansible.builtin.find:
    paths: "{{ role_path }}/stacks/all"
    file_type: directory
  delegate_to: localhost
  register: common_stacks_list
- name: Deploy common stacks
  when: common_stacks.stat.exists
  loop: "{{ common_stacks_list.files }}"
  ansible.builtin.include_tasks:
    file: deploy_stack.yml
  vars:
    stack_path: "{{ item.path }}"

- name: Check if there are any host stacks
  ansible.builtin.stat:
    path: "{{ role_path }}/stacks/{{ inventory_hostname }}"
  delegate_to: localhost
  register: host_stacks
- name: Check if there are host stack prerequisites
  when: host_stacks.stat.exists
  ansible.builtin.stat:
    path: "{{ role_path }}/stacks/{{ inventory_hostname }}/prerequisite.yml"
  delegate_to: localhost
  register: host_stacks_prerequisites
- name: Execute host stack prerequisites
  when: host_stacks.stat.exists and host_stacks_prerequisites.stat.exists
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/stacks/{{ inventory_hostname }}/prerequisite.yml"
- name: "DBG"
  ansible.builtin.debug:
    msg: "{{ host_stacks.stat.exists }}, {{ host_stacks_prerequisites.stat.exists }}"
- name: List host stacks
  when: host_stacks.stat.exists
  ansible.builtin.find:
    paths: "{{ role_path }}/stacks/{{ inventory_hostname }}"
    file_type: directory
  delegate_to: localhost
  register: host_stacks_list
- name: Deploy host stacks
  when: host_stacks.stat.exists
  loop: "{{ host_stacks_list.files }}"
  ansible.builtin.include_tasks:
    file: deploy_stack.yml
  vars:
    stack_path: "{{ item.path }}"
